# Generated by Django 4.2.3 on 2023-07-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('vocabulary', 'language', 'translation')},
        ),
    ]
