# Generated by Django 4.2.3 on 2023-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0002_alter_wordtranslation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('vocabulary', 'translation')},
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language',
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='language',
            field=models.ManyToManyField(to='VocabTrainer.language'),
        ),
    ]
