# Generated by Django 4.2.3 on 2023-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0004_alter_wordtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='languages',
            field=models.ManyToManyField(blank=True, to='VocabTrainer.language'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='meanings',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language_to',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='translation',
        ),
    ]
