# Generated by Django 4.2.3 on 2023-07-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0005_alter_wordtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtranslation',
            name='meanings',
        ),
    ]
