# Generated by Django 4.2.3 on 2023-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0006_remove_wordtranslation_meanings'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtranslation',
            name='translation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
