# Generated by Django 4.2.3 on 2023-07-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0007_wordtranslation_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtranslation',
            name='languages',
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='language_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
    ]
