# Generated by Django 4.2.3 on 2023-07-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0008_remove_wordtranslation_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language_to',
        ),
    ]
