# Generated by Django 4.2.3 on 2023-07-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0009_remove_wordtranslation_language_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtranslation',
            name='language_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('vocabulary', 'language_to', 'translation')},
        ),
    ]
