# Generated by Django 4.2.3 on 2023-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0010_wordtranslation_language_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='answer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language_to',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='translation',
        ),
    ]
