# Generated by Django 4.2.3 on 2023-07-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0012_rename_word_wordphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordphrase',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
        migrations.AlterUniqueTogether(
            name='wordphrase',
            unique_together={('word', 'language')},
        ),
    ]
