# Generated by Django 4.2.3 on 2023-07-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0013_wordphrase_language_alter_wordphrase_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtranslation',
            name='answer',
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='language_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
