# Generated by Django 4.2.3 on 2023-07-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0014_remove_wordtranslation_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordphrase',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wordphrase',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
    ]
