# Generated by Django 4.2.3 on 2023-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0015_alter_wordphrase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordphrase',
            name='word_dt',
            field=models.CharField(default='', max_length=50),
        ),
    ]
