# Generated by Django 4.2.3 on 2023-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0017_translation_word_translation_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=50),
        ),
    ]
