# Generated by Django 4.2.3 on 2023-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0019_rename_languages_word_translations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language_to',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='translation',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translation',
            field=models.ManyToManyField(blank=True, to='VocabTrainer.language'),
        ),
    ]
