# Generated by Django 4.2.3 on 2023-07-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0020_remove_word_translations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordtranslation',
            name='translation',
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='translation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
    ]
