# Generated by Django 4.2.3 on 2023-07-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0022_wordtranslation_language_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.wordphrase')),
            ],
        ),
    ]
