# Generated by Django 4.2.3 on 2023-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0023_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
