# Generated by Django 4.2.3 on 2023-07-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0024_translation_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language'),
        ),
    ]
