# Generated by Django 4.2.3 on 2023-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0025_translation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordphrase',
            name='language',
            field=models.CharField(default='en', max_length=4),
        ),
    ]
