# Generated by Django 4.2.3 on 2023-07-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0026_alter_wordphrase_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractWord',
            fields=[
                ('word_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('definition', models.CharField(blank=True, max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.language2')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.abstractword')),
            ],
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='Language1',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
