# Generated by Django 4.2.3 on 2023-07-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0027_abstractword_language2_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractword',
            name='abstract_word',
            field=models.CharField(default='', max_length=100),
        ),
    ]
