# Generated by Django 4.2.3 on 2023-07-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0028_abstractword_abstract_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language2',
            new_name='Language',
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='language_to',
        ),
        migrations.RemoveField(
            model_name='wordtranslation',
            name='vocabulary',
        ),
        migrations.DeleteModel(
            name='Language1',
        ),
        migrations.DeleteModel(
            name='WordPhrase',
        ),
        migrations.DeleteModel(
            name='WordTranslation',
        ),
    ]
