# Generated by Django 4.2.3 on 2023-07-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VocabTrainer', '0029_rename_language2_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractword',
            name='abstract_word',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VocabTrainer.abstractword', to_field='abstract_word'),
        ),
    ]
